### ISSUE TITLE
Boost 1.58.0 has been released

### ISSUE THREAD

**Issue by Towerism** [Manu343726/boost-biicode#16]
Please add support for Boost 1.58.0.  Currently I am overriding the boost version to download 1.58.0, but it would be nice to not have to do that.

**Comment by Manu343726** [comment]
Well, that's my fault. 1.58.0 was included in the ci tests since the beta release, but no biicode block tagged as `1.58.0` was released. Give me a minute. Thanks for the advise.

**Comment by Manu343726** [comment]
[Voilá!](https://www.biicode.com/biicode/biicode/boost/1.58.0). Please try it first before closing this, just to be sure it works well.

**Comment by Towerism** [comment]
Works great!  Thanks!
